name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run Tests
      run: dotnet test

    - name: Install AWS Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Build Lambda package
      run: dotnet lambda package --configuration Release --framework net8.0 --output-package bin/Release/netcoreapp/package.zip

    - name: Update Lambda
      uses: kazimanzurrashid/aws-lambda-update-action@v1
      with:
        zip-file: bin/Release/netcoreapp/package.zip
        lambda-name: CaptainRexEbooksFunction
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
